### ISSUE TITLE
Unable to run both read or write to DynamoDB local

### ISSUE THREAD

**Issue by dotekien** [awslabs/emr-dynamodb-connector#110]
I setup the DynamoDB locally following https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html and able to write and read DynamoDB locally using Dynamo API

With sparkSession like this: SparkSession.builder().master("local").getOrCreate()

The read or write to DynamoDB just hang at saveAsHadoopDataset() or hadoopRDD()  without any exception.

Could someone help me? Thanks

**Comment by PoeppingT** [comment]
Hi @dotekien thanks for your question!

Did you correctly set up your JobConf to use the emr-dynamodb-connector OutputFormat? Were there any log lines present in your local Spark master's logfile?

**Comment by praetp** [comment]
Is this a supported feature ? We would like to see this working.
Now I get errors like:

> 
> java.nio.file.NoSuchFileException: /mnt/var/lib/info/job-flow.json
> 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
> 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
> 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
> 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
> 	at java.nio.file.Files.newByteChannel(Files.java:361)
> 	at java.nio.file.Files.newByteChannel(Files.java:407)
> 	at java.nio.file.Files.readAllBytes(Files.java:3152)
> 	at org.apache.hadoop.dynamodb.util.ClusterTopologyNodeCapacityProvider.readJobFlowJsonString(ClusterTopologyNodeCapacityProvider.java:103)
> 	at org.apache.hadoop.dynamodb.util.ClusterTopologyNodeCapacityProvider.getCoreNodeMemoryMB(ClusterTopologyNodeCapacityProvider.java:42)
> 	at org.apache.hadoop.dynamodb.util.TaskCalculator.getMaxMapTasks(TaskCalculator.java:54)
> 	at org.apache.hadoop.dynamodb.DynamoDBUtil.calcMaxMapTasks(DynamoDBUtil.java:273)
> 	at org.apache.hadoop.dynamodb.write.WriteIopsCalculator.calculateMaxMapTasks(WriteIopsCalculator.java:78)
> 	at org.apache.hadoop.dynamodb.write.WriteIopsCalculator.<init>(WriteIopsCalculator.java:61)
> 	at org.apache.hadoop.dynamodb.write.AbstractDynamoDBRecordWriter.<init>(AbstractDynamoDBRecordWriter.java:85)
> 	at org.apache.hadoop.dynamodb.write.DefaultDynamoDBRecordWriter.<init>(DefaultDynamoDBRecordWriter.java:27)
> 	at org.apache.hadoop.dynamodb.write.DynamoDBOutputFormat.getRecordWriter(DynamoDBOutputFormat.java:30)
> 	at org.apache.spark.internal.io.HadoopMapRedWriteConfigUtil.initWriter(SparkHadoopWriter.scala:230)
> 	at org.apache.spark.internal.io.SparkHadoopWriter$.org$apache$spark$internal$io$SparkHadoopWriter$$executeTask(SparkHadoopWriter.scala:120)
> 	at org.apache.spark.internal.io.SparkHadoopWriter$$anonfun$3.apply(SparkHadoopWriter.scala:83)
> 	at org.apache.spark.internal.io.SparkHadoopWriter$$anonfun$3.apply(SparkHadoopWriter.scala:78)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:123)
> 	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by SagarBhatia0105** [comment]
@praetp were you able to resolve this?

**Comment by dshao9** [comment]
Seems like this is a duplicate issue of #50

**Comment by tao-pr** [comment]
Got the same issue when trying to access DynamoDB from local instance. Dependencies loaded in runtime ok, but when trying to materialise the RDD, it crashes with the exception as OP posted.

Surprises me as this issue was since 8.2019, and I'm still facing it with latest release
