### ISSUE TITLE
Question on RequestLimitExceededException

### ISSUE THREAD

**Issue by dlylitsuka** [awslabs/emr-dynamodb-connector#133]
Hello, I have some dumb questions to ask around a recent RequestLimitExceededException. We have a Hive job to inject S3 data to dynamoDB and recently we have a set of data consistently getting RequestLimitExceededException. The configuration details can be found below:

DynamoDB table: On-Demand
Tez: --hiveconf tez.grouping.max-size=2097152 --hiveconf tez.grouping.min-size=1048576 --hiveconf dynamodb.throughput.write.percent=1.0
Part of the logs:
`Map 1: 0(+64,-119)/64	
Map 1: 0(+64,-121)/64	
Map 1: 0(+64,-125)/64	
Map 1: 0(+64,-126)/64	
Map 1: 0(+0,-127)/64	
Status: Failed
Vertex failed, vertexName=Map 1, vertexId=vertex_1597788812275_0027_8_00, diagnostics=[Task failed, taskId=task_1597788812275_0027_8_00_000029, diagnostics=[TaskAttempt 0 failed, info=[Error: Error while running task ( failure ) : attempt_1597788812275_0027_8_00_000029_0:java.lang.RuntimeException: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row <removed>
	at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.initializeAndRunProcessor(TezProcessor.java:211)
	at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.run(TezProcessor.java:168)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:374)
	at org.apache.tez.runtime.task.TaskRunner2Callable$1.run(TaskRunner2Callable.java:73)
	at org.apache.tez.runtime.task.TaskRunner2Callable$1.run(TaskRunner2Callable.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
	at org.apache.tez.runtime.task.TaskRunner2Callable.callInternal(TaskRunner2Callable.java:61)
	at org.apache.tez.runtime.task.TaskRunner2Callable.callInternal(TaskRunner2Callable.java:37)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row <removed>
	at org.apache.hadoop.hive.ql.exec.tez.MapRecordSource.processRow(MapRecordSource.java:95)
	at org.apache.hadoop.hive.ql.exec.tez.MapRecordSource.pushRecord(MapRecordSource.java:70)
	at org.apache.hadoop.hive.ql.exec.tez.MapRecordProcessor.run(MapRecordProcessor.java:419)
	at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.initializeAndRunProcessor(TezProcessor.java:185)
	... 14 more
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row <removed>
	at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:565)
	at org.apache.hadoop.hive.ql.exec.tez.MapRecordSource.processRow(MapRecordSource.java:86)
	... 17 more
Caused by: java.lang.RuntimeException: com.amazonaws.services.dynamodbv2.model.RequestLimitExceededException: Throughput exceeds the current throughput limit for your account. Please contact AWS Support at https://aws.amazon.com/support request a limit increase (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: RequestLimitExceeded; Request ID: DERHFJO1RLGO68L30SFBEQF1UBVV4KQNSO5AEMVJF66Q9ASUAAJG)
	at org.apache.hadoop.dynamodb.DynamoDBFibonacciRetryer.handleException(DynamoDBFibonacciRetryer.java:108)
	at org.apache.hadoop.dynamodb.DynamoDBFibonacciRetryer.runWithRetry(DynamoDBFibonacciRetryer.java:83)
	at org.apache.hadoop.dynamodb.DynamoDBClient.writeBatch(DynamoDBClient.java:258)
	at org.apache.hadoop.dynamodb.DynamoDBClient.putBatch(DynamoDBClient.java:215)
	at org.apache.hadoop.dynamodb.write.AbstractDynamoDBRecordWriter.write(AbstractDynamoDBRecordWriter.java:112)
	at org.apache.hadoop.hive.dynamodb.write.HiveDynamoDBRecordWriter.write(HiveDynamoDBRecordWriter.java:42)
	at org.apache.hadoop.hive.ql.exec.FileSinkOperator.process(FileSinkOperator.java:762)
	at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:897)
	at org.apache.hadoop.hive.ql.exec.SelectOperator.process(SelectOperator.java:95)
	at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:897)
	at org.apache.hadoop.hive.ql.exec.TableScanOperator.process(TableScanOperator.java:130)
	at org.apache.hadoop.hive.ql.exec.MapOperator$MapOpCtx.forward(MapOperator.java:148)
	at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:550)
	... 18 more`

With the same configurations, we've run large data set/more concurrent mappers before and those completed with no issues. What could be the possible reasons failed this one I should look for? Also we saw this one has a bunch of failed tasks, how should I understand the effects to this issue from failed tasks? 

Any hints is really appreciated.

**Comment by sivankumar86** [comment]
are there any clients using dynamodb ? there many reasons for throttle exception like hot partition,GSI throttle etc.. 

Could you try with --hiveconf dynamodb.throughput.write.percent=0.9 0r 0.8. Also, check throttle metrics on table for more details. 

When you set 1.0, it means, 100% table capacity assigned to connector and make sure that there is no other client writing to table.
