### ISSUE TITLE
Large items in table break serialization

### ISSUE THREAD

**Issue by dandersonw** [awslabs/emr-dynamodb-connector#66]
If I run the below:

`pyspark --jars /usr/share/aws/emr/ddb/lib/emr-ddb-hadoop.jar`
```python
conf = {
    "dynamodb.servicename": "dynamodb",
    "dynamodb.input.tableName": "table_with_big_items_in_it",
    "dynamodb.endpoint": "https://dynamodb.ap-northeast-1.amazonaws.com",
    "dynamodb.regionid": "ap-northeast-1",    "mapred.output.format.class": "org.apache.hadoop.dynamodb.write.DynamoDBOutputFormat",
    "mapred.input.format.class": "org.apache.hadoop.dynamodb.read.DynamoDBInputFormat"
}

rdd = sc.hadoopRDD(
    inputFormatClass='org.apache.hadoop.dynamodb.read.DynamoDBInputFormat',
    keyClass='org.apache.hadoop.io.Text',
    valueClass='org.apache.hadoop.dynamodb.DynamoDBItemWritable',
    conf=conf
)
rdd.take(1)
```
I get the following error:
```
8/03/15 09:04:36 WARN TaskSetManager: Lost task 0.0 in stage 11.0 (TID 26, ip-172-31-141-34.ap-northeast-1.compute.internal, executor 9): java.lang.RuntimeException: Error writing/reading clone buffer
	at org.apache.hadoop.io.WritableUtils.clone(WritableUtils.java:221)
	at org.apache.spark.api.python.WritableToJavaConverter.org$apache$spark$api$python$WritableToJavaConverter$$convertWritable(PythonHadoopUtil.scala:93)
	at org.apache.spark.api.python.WritableToJavaConverter.convert(PythonHadoopUtil.scala:101)
	at org.apache.spark.api.python.PythonHadoopUtil$$anonfun$convertRDD$1.apply(PythonHadoopUtil.scala:181)
	at org.apache.spark.api.python.PythonHadoopUtil$$anonfun$convertRDD$1.apply(PythonHadoopUtil.scala:181)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:121)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:112)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.foreach(SerDeUtil.scala:112)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:518)
	at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:333)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1948)
	at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:269)
Caused by: java.io.UTFDataFormatException: encoded string too long: 84878 bytes
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:364)
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
	at org.apache.hadoop.dynamodb.DynamoDBItemWritable.write(DynamoDBItemWritable.java:53)
	at org.apache.hadoop.io.serializer.WritableSerialization$WritableSerializer.serialize(WritableSerialization.java:98)
	at org.apache.hadoop.io.serializer.WritableSerialization$WritableSerializer.serialize(WritableSerialization.java:82)
	at org.apache.hadoop.util.ReflectionUtils.copy(ReflectionUtils.java:298)
	at org.apache.hadoop.io.WritableUtils.clone(WritableUtils.java:218)
	... 14 more
```
As far as I can tell the problem is that the [method](https://docs.oracle.com/javase/8/docs/api/java/io/DataOutput.html#writeUTF-java.lang.String-) used [here](https://github.com/awslabs/emr-dynamodb-connector/blob/master/emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBItemWritable.java#L53) is limited to strings of 65535 bytes or less. DynamoDB items can be 400KB though - a fact that we take advantage of to store documents that can be a few hundred kilobytes in size.

Interestingly, if I run the following using the Scala shell:
`spark-shell --jars /usr/share/aws/emr/ddb/lib/emr-ddb-hadoop.jar`
```scala
import org.apache.hadoop.io.Text;
import org.apache.hadoop.dynamodb.DynamoDBItemWritable
import org.apache.hadoop.dynamodb.read.DynamoDBInputFormat
import org.apache.hadoop.dynamodb.write.DynamoDBOutputFormat
import org.apache.hadoop.mapred.JobConf

var jobConf = new JobConf(sc.hadoopConfiguration)
jobConf.set("dynamodb.servicename", "dynamodb")
jobConf.set("dynamodb.input.tableName", "table_with_big_items_in_it")
jobConf.set("dynamodb.endpoint", "dynamodb.ap-northeast-1.amazonaws.com")
jobConf.set("dynamodb.regionid", "ap-northeast-1")
jobConf.set("mapred.output.format.class", "org.apache.hadoop.dynamodb.write.DynamoDBOutputFormat")
jobConf.set("mapred.input.format.class", "org.apache.hadoop.dynamodb.read.DynamoDBInputFormat")


var elements = sc.hadoopRDD(jobConf, classOf[DynamoDBInputFormat], classOf[Text], classOf[DynamoDBItemWritable])

elements.values.take(1)
```
It seems to work fine. Looking at the first stack trace, it does seem like a proximate cause of the error is code in `org.apache.spark.api.python`. Why the issue doesn't come up in Scala I don't know. Either way, I probably shouldn't introduce Scala into our stack and so if anyone has an idea about getting the DynamoDB connector to work for large items in Python I'm all ears.

**Comment by dandersonw** [comment]
I asked myself what was the most braindead fix I could imagine, implemented it as the below:
```
@@ -45,12 +47,28 @@ public class DynamoDBItemWritable implements Writable, Serializable {
   // format itself and make sure that's backward compatible.
   @Override
   public void readFields(DataInput in) throws IOException {
-    readFieldsStream(in.readUTF());
+    int chunks = in.readInt();
+    String whole = "";
+    for (int c = 0; c < chunks; c++) {
+        String chunk = in.readUTF();
+        whole += chunk;
+    }
+    readFieldsStream(whole);
   }

   @Override
   public void write(DataOutput out) throws IOException {
-    out.writeUTF(writeStream());
+    String whole = writeStream();
+    int chunkSize = 1 << 14;
+    int chunks = whole.length() / chunkSize;
+    if (whole.length() % chunkSize != 0) {
+        chunks += 1;
+    }
+    out.writeInt(chunks);
+    for (int c = 0; c < chunks; c++){
+        String chunk = whole.substring(c * chunkSize, Math.min((c + 1) * chunkSize, whole.length()));
+        out.writeUTF(chunk);
+    }
   }
```
and it worked.

Obviously the above is not backwards compatible. I do though have in mind some black magic to implement a backwards compatible solution - stay tuned for a PR.

**Comment by itsgrimetime** [comment]
Thanks for the PR, @dandersonw!
