### ISSUE TITLE
pyspark examples ? 

### ISSUE THREAD

**Issue by anandhs** [awslabs/emr-dynamodb-connector#91]
Can we get some examples added to read and write from dynamodb using pyspark ? 

Here is what I have tried so far on  a standalone spark cluster ( not EMR ) 

``` 
conf = {
    "dynamodb.servicename": "dynamodb",
    "dynamodb.input.tableName": "test",
    "dynamodb.output.tableName": "test",
    "dynamodb.endpoint": "http://localhost:4569",
    "dynamodb.regionid": "us-east-1",
    "mapred.output.format.class": "org.apache.hadoop.dynamodb.write.DynamoDBOutputFormat",
    "mapred.input.format.class": "org.apache.hadoop.dynamodb.read.DynamoDBInputFormat"
}

sc = spark.sparkContext

sc.hadoopRDD(
	inputFormatClass='org.apache.hadoop.dynamodb.read.DynamoDBInputFormat',
	keyClass='org.apache.hadoop.io.Text',
	valueClass='org.apache.hadoop.dynamodb.DynamoDBItemWritable',
	conf=conf
)

2019-02-14 14:33:50 WARN  ClusterTopologyNodeCapacityProvider:51 - Exception when trying to determine instance types
java.nio.file.NoSuchFileException: /mnt/var/lib/info/job-flow.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at org.apache.hadoop.dynamodb.util.ClusterTopologyNodeCapacityProvider.readJobFlowJsonString(ClusterTopologyNodeCapacityProvider.java:103)
	at org.apache.hadoop.dynamodb.util.ClusterTopologyNodeCapacityProvider.getCoreNodeMemoryMB(ClusterTopologyNodeCapacityProvider.java:42)


```

I tried with v4.6.0 of the connector library.

**Comment by rentaow** [comment]
Looks like it's trying to access files specific to EMR clusters. For non EMR clusters, ClusterTopologyNodeCapacityProvider would need some change to not rely on the job-flow.json file.

**Comment by SwethaMandala** [comment]
Are you able to write to Dynamo DB sing pyspark? Can you please share the samples?

**Comment by sivankumar86** [comment]
seems, You need to run it in EMR. There is a request for non emr env support. 
https://github.com/awslabs/emr-dynamodb-connector/issues/50
